### ISSUE TITLE
Consider using scribe backend

### ISSUE THREAD

**Issue by DavidGregory084** [ChristopherDavenport/log4cats#1]
Hey @ChristopherDavenport, this is a really nice project! Looks great!

I was wondering whether you'd consider a PR to use [outr/scribe](https://github.com/outr/scribe) rather than log4s or making the logging backend configurable? scribe has support for scala-native / scala.js and great performance, and it can still be used as an slf4j backend.

**Comment by ChristopherDavenport** [comment]
I would definitely consider it. After thinking about constraints I'm wondering whether we could abstract the fundamental algebra or something similar and then have backends which implement in different modules so it operates to each teams individual taste. 

How do you feel about the structure of the algebra, as it seems fairly consistent across the logging libraries?

**Comment by DavidGregory084** [comment]
Yeah, it looks good to me - certainly covers everything that I'd use personally :+1:
