### ISSUE TITLE
History logger for testing convenience 

### ISSUE THREAD

**Issue by keirlawson** [ChristopherDavenport/log4cats#11]
In some sections of our codebase we've found ourselves wanting to check that code is infact logging the way we expect.  To do this with Journal we built a `HistoryLogger` along these lines (apologies for the lack of purity ;-) ):

```scala
class HistoryLogger(private val enableDebug: Boolean = true) {
  val messages = mutable.MutableList[String]()

  private val slf4jBackend =
    new SubstituteLogger("test", new java.util.LinkedList(), false) {
      override def isInfoEnabled = true

      override def isWarnEnabled = true

      override def isErrorEnabled = true

      override def isDebugEnabled = enableDebug

      override def info(msg: String): Unit = messages += msg

      override def warn(msg: String): Unit = messages += msg

      override def error(msg: String): Unit = messages += msg

      override def debug(msg: String): Unit = messages += msg
    }
  slf4jBackend.setDelegate(NOPLogger.NOP_LOGGER)

}
```

This allows us to pass in this logger and then assert that the expected message has been logged.  Perhaps it could be useful to have a testing logger such as this built in to log4cats if this is a sufficiently wide use-case?

**Comment by keirlawson** [comment]
Looks like log4s has a version of this: https://github.com/Log4s/log4s#log4s-testing - so I'm not sure if we would want to create something similar in log4cats or just leave people to use the log4s version, which I guess has the downside of being impure

**Comment by ChristopherDavenport** [comment]
So I should be able to implement this for methods that take loggers as an argument, if you want to check was has been dispatched on the back that is more difficult.
