### ISSUE TITLE
cats-mtl module with FunctorTellLogger and automatic MDC injection

### ISSUE THREAD

**Issue by bplommer** [ChristopherDavenport/log4cats#143]
A cats-mtl module could provide a couple of useful things:

- A logger based on `StructuredLogger` that automatically adds MDC context from an `ApplicativeAsk` instance.
- A logger similar to `WriterTLogger` but based on `FunctorTell` for extra flexibility.

I'd be happy to put in a PR if this would be wanted.

**Comment by oscarvarto** [comment]
@bplommer I am interested in how your implementation would be (still learning about cats-mtl)

**Comment by ChristopherDavenport** [comment]
https://github.com/ChristopherDavenport/log4cats-mtl - Exists and is released
