### ISSUE TITLE
Direct SLF4J backend

### ISSUE THREAD

**Issue by keirlawson** [ChristopherDavenport/log4cats#17]
For projects which might use log4cats as their only logging interface, the additional layer of abstraction that is log4s seems unnecessary, would it be possible to build a direct SLF4J backend to log4cats?

**Comment by ChristopherDavenport** [comment]
So generally things utilize macros for the log4s implementations. What sort of a direct system do you invision? Something along the lines of implementing to macros to operate initially in F?

**Comment by keirlawson** [comment]
I'm not sure I have suggestions in terms of how this might be implemented as I have no experience with macros, my intuition was just that it feels like log4cats -> log4s -> slf4j -> logback is probably more layers of abstraction than we need...

**Comment by rossabaker** [comment]
slf4j-api carries its weight so you don't need to reimplement every logging backend under the sun.  I'm surprised this has any layers on top of that.  Though I totally understand it being bootstrapped this way.
