### ISSUE TITLE
Add means to test whether debug logging is enabled

### ISSUE THREAD

**Issue by keirlawson** [ChristopherDavenport/log4cats#2]
When attempting to port our application from Journal to log4cats 0.0.1 the first issue I encountered was there appears to be no way to test whether or not debug logging is enabled.  We achieved this in Journal by using `Logger.backend.isDebugEnabled`.

**Comment by ChristopherDavenport** [comment]
So questioning, we want this as an attribute of the logger? I'm tempted to expose the underlying `A` within the algebra. However this is currently an artifactor of utilizing log4s so closely. It sounds like  perhaps it would serve to build a core component with modules depending on the backends.

**Comment by keirlawson** [comment]
This strikes me as a fairly generic feature common to most loggers and fairly commonly used, so my preference would be to expose it as part of the log4cats logger without requiring a reference to the underlying implementation.
