### ISSUE TITLE
What is the suggested way to use this library?

### ISSUE THREAD

**Issue by araknafobia** [ChristopherDavenport/log4cats#267]
There are two approaches mentioned in the README.md and I am a bit confused at this point. There reason is that; it looks like that first approach is impure and second approach (if I am not mistaken) creates a logger every time you use it in for comprehension.

Would it make sense to treat logger as `Resource`?

```
val logger: Resource[F, SelfAwareStructuredLogger[F]] = Resource.liftF(Slf4jLogger.fromClass[F](this.getClass))

def safelyDoThings[F[_]: Sync]: F[Unit] = for {
    _ <- logger.use(_.info("Logging at start of safelyDoThings"))
    something <- Sync[F].delay(println("I could do anything"))
      .onError{case e => logger.use(_.error(e)("Something Went Wrong in safelyDoThings"))}
    _ <- logger.use(_.info("Logging at end of safelyDoThings"))
  } yield something

```

I am still new to whole TypeLevel/FP stack so please let me know if I am doing something completely wrong.

**Comment by ChristopherDavenport** [comment]
My suggested approach is rather than logging in 1 space, to create a singular logger for the whole application which should be passed as a value.

I am working on a way to change the underlying logger name separately.

**Comment by araknafobia** [comment]
@ChristopherDavenport thanks for the clarification!

**Comment by rikvdkleij** [comment]
@ChristopherDavenport 

> to create a singular logger for the whole application which should be passed as a value.

In that solution every log line has the same context, i.e. the name of the class where the logger is created. 
Is there an elegant alternative (so without creating a logger for each class/object)?

**Comment by ChristopherDavenport** [comment]
There has been a proposal for us to allow a `withName` on loggers to shift the name under the hood. Currently there is

```
trait LoggerGen[F[_]]{
  def getLogger(name: String): F[StructuredLogger[F]]
}
```
