### ISSUE TITLE
No-op Logger

### ISSUE THREAD

**Issue by jkachmar** [ChristopherDavenport/log4cats#51]
Do you think it'd be useful to include a `Logger` that just acts as a no-op for any logging operations?

Mostly inspired by `monad-logger`'s [NoLoggingT](https://www.stackage.org/haddock/lts-11.15/monad-logger-0.3.28.5/Control-Monad-Logger.html#t:NoLoggingT), which I've used in testing scenarios when I just want to disable logging entirely for any functions using `MonadLogger`.

**Comment by ChristopherDavenport** [comment]
I can definitely add that.
