### ISSUE TITLE
Add changelog with version matching information

### ISSUE THREAD

**Issue by Daenyth** [ChristopherDavenport/log4cats#88]
I'm having a hard time figuring out right now which version of this is for which version of cats-effect. Having compat notes in the changelog would really help

**Comment by ChristopherDavenport** [comment]
Hopefully fixed by https://github.com/ChristopherDavenport/log4cats/commit/97de359c21513d96de3059d6d58d1b63dd68c3bd

Original baseline was for 0.1.x series was on cats-effect 0.10.1.
